version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "America/New_York"
    versioning-strategy: increase-if-necessary
